{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cigar.fullname" . }}
  labels:
    {{- include "cigar.labels" . | nindent 4 }}
type: Opaque
stringData:
  WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  WEBHOOK_SIGNING_TOKEN: {{ .Values.secrets.signingToken | default "" | quote }}
  GITLAB_TOKEN: {{ .Values.secrets.gitlabToken | quote }}
{{- end }}
